### ISSUE TITLE
Minor fix in demo.py

### ISSUE THREAD

**Issue by ojhaarjun1** [AkariAsai/learning_to_retrieve_reasoning_paths#1]
Hi,

Thank you for your amazing work. While running demo.py, I encountered a simple bug.
Line 44:
```
tfidf_retrieval_output += self.tfidf_retriever.get_abstract_tfidf('DEMO_{}'.format(i), question, self.args.tfidf_limit)
```
should be
```
tfidf_retrieval_output += self.tfidf_retriever.get_abstract_tfidf('DEMO_{}'.format(i), question, self.args)
```
as get_abstract_tfidf(...) expects args as the last argument.

**Comment by hassyGo** [comment]
Hi,

Thank you so much for trying our demo, and pointing out the bug!
We have fixed the bug as follows:
https://github.com/AkariAsai/learning_to_retrieve_reasoning_paths/blob/master/demo.py#L44

Thanks again.

**Comment by AkariAsai** [comment]
Thank you for reporting @ojhaarjun1 . We've fixed the bug and I close this issue.
