### ISSUE TITLE
Some details regarding generating NQ trainset for the reader model

### ISSUE THREAD

**Issue by mjeensung** [AkariAsai/learning_to_retrieve_reasoning_paths#10]
Hi @AkariAsai. Thank you for this great work.

I'd like to understand more clearly how the NQ trainset for the reader model is generated.
On your comment, you said that you removed all the tables and list elements from the NQ's original preprocessed HTML data.
https://github.com/AkariAsai/learning_to_retrieve_reasoning_paths/issues/9#issuecomment-610714692

I'm curious how you handled the case where a list element contains an answer and a paragraph contains the list?  (like the following example)
https://github.com/google-research-datasets/natural-questions/blob/master/toy_example.md

eg. `<p>Google was founded in 1998 By:<ul><li>Larry</li><li>Sergey</li></ul></p>`

**Comment by mjeensung** [comment]
Did you remove such examples? 
Or did you just remove the 'list' tag so that the example is parsed like : 
`Google was founded in 1998 By: Larry Sergey`

**Comment by AkariAsai** [comment]
Addressing your main question,  we do not filter out the lists inside paragraphs, but we remove any HTML tags remaining in the context during our post-process. Thus, the example you mentioned above would be  `Google was founded in 1998 By: Larry Sergey`, but there might be some corner cases we missed.

**Comment by mjeensung** [comment]
Thank you for the quick response. It's of great help to me.

I'm also wondering if you may have applied additional filtering conditions (such as the length of answer tokens).

**Comment by AkariAsai** [comment]
We do not apply additional filtering conditions based on the answer length. Our train/dev/test splits are from [A Discrete Hard EM Approach for Weakly Supervised Question Answering's original repository](https://github.com/shmsw25/qa-hard-em), and in [their preprocess script](https://github.com/shmsw25/qa-hard-em/blob/master/split_nq.py), the answers whose length is larger than five are filtered out, as in [another previous work](https://arxiv.org/abs/1906.00300).

**Comment by mjeensung** [comment]
Thank you for the information!

**Comment by AkariAsai** [comment]
No problem! Thank you for your interest in our work :)
