### ISSUE TITLE
Inconsistent  'answers' types in the nq_reader_train data

### ISSUE THREAD

**Issue by mjeensung** [AkariAsai/learning_to_retrieve_reasoning_paths#12]
I found that a few 'answers' which are distantly supervised have 'dict' types while most of the 'answers' have 'list' types as values.

Example.
![image](https://user-images.githubusercontent.com/44629366/79038060-650f2100-7c11-11ea-9769-fb236003e0f2.png)
![image](https://user-images.githubusercontent.com/44629366/79038064-6e988900-7c11-11ea-8acd-782a2f7ae8dd.png)

**Comment by AkariAsai** [comment]
Thank you for reporting. We will fix it.
