### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ukab23** [AkariAsai/learning_to_retrieve_reasoning_paths#17]
Experiencing this error while training graph retriever over hotpotqa data 
jsn = json.load(open(file_name, 'r', encoding="utf-8", errors='ignore', newline='\n'))
learning_to_retrieve_reasoning_paths/graph_retriever/utils.py", line 232

**Comment by AkariAsai** [comment]
Hi, thanks for the comment. You are trying to use `hotpotqa_new_selector_train_data_db_2017_10_12_fix` located [here](https://drive.google.com/drive/u/1/folders/19rGhtUvBkyt4kOmlEpLY3fVwCbKyluSA), right? 
Did you unzip the data before feeding it out codes?
