### ISSUE TITLE
Fine-tuning on own documents? 

### ISSUE THREAD

**Issue by tmontana** [AkariAsai/learning_to_retrieve_reasoning_paths#18]
Hi - what would be the recommended approach for fine tuning (not full retrain) of the model on one's own documents?

Thank you

**Comment by AkariAsai** [comment]
Hi, thanks for your interest in our work! I think as long as you convert your own data into[ the same format as the retriever training data](https://github.com/AkariAsai/learning_to_retrieve_reasoning_paths#format-b-tf-idf-retriever-output), you can fine-tuning on your own document. Note that our retriever omits the tokens exceeding the maximum token limitations as BERT cannot process longer than 512 sub-tokens. That said, to get the best performance, It may be better to split your documents less than the maximum token limitations. 
 
While you can start from scratch (start training using `bert-base-cased` or `bert-base-uncased`), you can start fine-tuning from our NQ / SQuAD / HotpotQA checkpoint. I think you can do that by setting `--bert_model` to the path to the checkpoint directory. We recommend you using the checkpoints trained on the dataset that is most similar to your own data. If your data requires a lot of multi-hop reasoning and has some bias towards entities, the checkpoints trained on HotpotQA may be the most suitable one to start fine-tuning with. If your data has a relatively limited lexical overlap between questions and paragraphs, the one trained on NQ may be better to be adapted. 

Please let me know if you have any followup questions!

**Comment by AkariAsai** [comment]
I'll close this issue now but please feel free to re-open if you have any questions!
