### ISSUE TITLE
Evaluation input for retriever

### ISSUE THREAD

**Issue by tbright17** [AkariAsai/learning_to_retrieve_reasoning_paths#2]
Hi,

Thanks for sharing the code. Wondering which file should I use if I want to get the output of graph retriever using hotpot_dev_fullwiki_v1.json? Looks like the code only takes input in SQuAD 2.0 format. Please let me know where I can download processed hotpot_dev_fullwiki data.

Thanks

**Comment by AkariAsai** [comment]
> Wondering which file should I use if I want to get the output of graph retriever using hotpot_dev_fullwiki_v1.json? 

To run the full pipeline, you can use our preprocessed HotpotQA dev full wiki data from [here](https://drive.google.com/drive/u/1/folders/1na7vxYWadK2kS2aqg88RDMFir8PP-2lS) (the file name is `hotpot_fullwiki_data.jsonl`). 

If you specify the output file path of the graph retriever module (`--selector_results_save_path`) and run `eval_main.py`, the output result will be stored as a `JSON`.

> Looks like the code only takes input in SQuAD 2.0 format. 
The reader takes SQuAD 2.0 format. If you are looking for a preprocessed reader file to train reader component, you can download preprocessed file (in SQuAD 2.0) format [here](https://drive.google.com/drive/u/1/folders/1nzuo7i9ghpKd-FbELhkWQT0p_yqF6UF4) (the file name is `hotpot_reader_train_data.json`). 


To make the whole train and eval process consistent across three different datasets, we do not primarily use the original dev/train files in three different formats as the input file of our evaluation pipeline, and convert them into a single format. Please see the details in [README.md](https://github.com/AkariAsai/learning_to_retrieve_reasoning_paths#dataset-format). 
All question-answer pairs are exactly the same as the original files.

**Comment by AkariAsai** [comment]
I'm closing this issue, but please feel free to re-open and reach us if you have any further questions! :)
