### ISSUE TITLE
What do output_masks do?

### ISSUE THREAD

**Issue by NoviScl** [AkariAsai/learning_to_retrieve_reasoning_paths#25]
Hi @AkariAsai ,

Thanks for the great repo!

I'm trying to adapt your model to a new dataset, I find that there is an output_masks in the graph_retriever/utils.py convert_examples_to_features function, may I check what exactly do the output_masks do? How should I set the masking for positive and negative reasoning paths? 

Also, may I clarify how did you set the gold labels for each RNN step, and for the negative paths? 

Thanks!

**Comment by AkariAsai** [comment]
Hi sorry for my late response, I think your understanding is correct! cc @hassyGo

**Comment by NoviScl** [comment]
No worries, already resolved the issue.
