### ISSUE TITLE
question about wikipedia data

### ISSUE THREAD

**Issue by jcyk** [AkariAsai/learning_to_retrieve_reasoning_paths#4]
Hi, thanks for sharing the code. Great work!

I have a quick question: Where can I find your preprocessed Wikipedia paragraphs and Wikipedia graph?

**Comment by hassyGo** [comment]
Hi, thank you for your interest in our project!

The Wikipedia paragraphs are stored in `.db` files, and you can find an example for the HotpotQA dataset in the script:
https://github.com/AkariAsai/learning_to_retrieve_reasoning_paths/blob/master/quick_start_hotpot.sh

**Comment by AkariAsai** [comment]
I close this issue now, but please re-open and let us know if you have any troubles finding or loading the data :)
