### ISSUE TITLE
hotpot model zip file corrupted?

### ISSUE THREAD

**Issue by liuzzi** [AkariAsai/learning_to_retrieve_reasoning_paths#7]
Hello, I haven't been able to unzip the hotpot model zip, and ive tried a few different methods.  Seems its corrupt in some way?  Has anybody else had a problem unzipping?
The squad models dont have a problem

**Comment by AkariAsai** [comment]
Thank you for reporting the issue! 

To understand the situation, I would like to ask you a few things:
1. Which URL link (a google drive URL) did you use to download the models? 
2. Which command did you use to extract the models (e.g., `unzip`)?
3. Could you share the error messages you got when you tried to extract the models?  Or what does "its corrupt in some way" mean?

**Comment by liuzzi** [comment]
sure, thanks for the quick response. 

I tried downloading both through the regular http process in google drive
e.g. clicking download here   
https://drive.google.com/open?id=1ra37xtEXSROG_f90XxR4kgElGJWUHQyM

and I also tried using the gdown program to download the hotpot models using the command:
gdown https://drive.google.com/uc?id=1ra37xtEXSROG_f90XxR4kgElGJWUHQyM

Both result in a file that's about 4gb and seems to download fine. 

First thing i did was try using the Ubuntu GUI to just extract it to the current folder and it gave a vague 'error extracting' error.

So then I went to the command prompt and tried   unzip    XXXX.zip
that results in a slightly more detailed error:  
'error: invalid zip file with overlapped components (possible zip bomb)'

Just to make sure something wasn't wrong on my side I booted up a windows computer in an attempt to use another extraction program, and the windows computer also says something vague like 'zip file corrupted'

**Comment by AkariAsai** [comment]
I have downloaded the `hotpot_models.zip` file into my macOS PC and also downloaded the same file to a CentOS machine via the gdown command. However, both seem to work for me as previously.
I do not have any Windows or Ubuntu machines right now, so not sure if the same errors can be reproduced on my side...

**Comment by AkariAsai** [comment]
I'll close this issue for now, but please let us know if you see further issues! :)

**Comment by liuzzi** [comment]
didn't get a chance until now to try it on a Mac machine, and that worked -- thanks

**Comment by AkariAsai** [comment]
Glad to know that! Sorry for the inconvenience. We'll make sure that we could download the files correctly in different machines next time.

**Comment by sysu-zjw** [comment]
I encountered the same error on CentOS and have solved it by using java archiver. Just try `jar xvf hotpot_models.zip`.
```
bash-4.2$ unzip hotpot_models.zip
Archive:  hotpot_models.zip
warning [hotpot_models.zip]:  4294967296 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  4294967296
  (attempting to re-compensate)
error: invalid zip file with overlapped components (possible zip bomb)
```

```
bash-4.2$ jar xvf hotpot_models.zip
  created: hotpot_models/
 inflated: hotpot_models/.DS_Store
  created: __MACOSX/
  created: __MACOSX/hotpot_models/
 inflated: __MACOSX/hotpot_models/._.DS_Store
  created: hotpot_models/graph_retriever_path/
 inflated: hotpot_models/graph_retriever_path/pytorch_model.bin
  created: __MACOSX/hotpot_models/graph_retriever_path/
 inflated: __MACOSX/hotpot_models/graph_retriever_path/._pytorch_model.bin
 inflated: __MACOSX/hotpot_models/._graph_retriever_path
  created: hotpot_models/reader/
 inflated: hotpot_models/reader/config.json
  created: __MACOSX/hotpot_models/reader/
 inflated: __MACOSX/hotpot_models/reader/._config.json
 inflated: hotpot_models/reader/pytorch_model.bin
 inflated: __MACOSX/hotpot_models/reader/._pytorch_model.bin
 inflated: hotpot_models/reader/vocab.txt
 inflated: __MACOSX/hotpot_models/reader/._vocab.txt
 inflated: __MACOSX/hotpot_models/._reader
  created: hotpot_models/sequential_sentence_selector/
 inflated: hotpot_models/sequential_sentence_selector/pytorch_model.bin
  created: __MACOSX/hotpot_models/sequential_sentence_selector/
 inflated: __MACOSX/hotpot_models/sequential_sentence_selector/._pytorch_model.bin
  created: hotpot_models/tfidf_retriever/
 inflated: hotpot_models/tfidf_retriever/wiki_open_full_new_db_intro_only-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz
  created: __MACOSX/hotpot_models/tfidf_retriever/
 inflated: __MACOSX/hotpot_models/tfidf_retriever/._wiki_open_full_new_db_intro_only-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz
  created: hotpot_models/wiki_db/
 inflated: hotpot_models/wiki_db/wiki_abst_only_hotpotqa_w_original_title.db
  created: __MACOSX/hotpot_models/wiki_db/
 inflated: __MACOSX/hotpot_models/wiki_db/._wiki_abst_only_hotpotqa_w_original_title.db
 inflated: __MACOSX/._hotpot_models
```
